# Generated by Django 5.1 on 2024-08-22 21:23

import apps.general.utils.uploaders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.general.utils.uploaders.food_uploader_directory, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
