services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  react:
    build:
      context: ./web/
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app/
    command: npm run dev

  bot:
    build: .
    command: python3 -m bot polling
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
