# Generated by Django 5.1 on 2024-08-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dashboard_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='dashboard_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
