# Generated by Django 5.1 on 2024-08-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_staff_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('cook', 'Шеф-повар'), ('manager', 'Менеджер'), ('ceo', 'Генеральный директор (CEO)')], max_length=255, null=True),
        ),
    ]
